# Generated by Django 4.2.1 on 2024-07-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Diagnosis", "0002_diagnosisresult_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosisresult",
            name="consent_status",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
