# Generated by Django 4.2.1 on 2024-08-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Diagnosis", "0003_diagnosisresult_consent_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosisresult",
            name="diabetes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="diagnosisresult",
            name="smoking",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
